# Generated by Django 4.2.27 on 2026-06-11 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0216_problemeditorialreveal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Quiz code must be ^[a-z0-9_]+$')], verbose_name='quiz code')),
                ('name', models.CharField(max_length=100, verbose_name='quiz name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=6, verbose_name='level')),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited time.', null=True, verbose_name='time limit (minutes)')),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited attempts.', null=True, verbose_name='maximum attempts')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='shuffle questions')),
                ('show_correctness', models.BooleanField(default=True, verbose_name='show correctness on result')),
                ('show_answers', models.BooleanField(default=True, verbose_name='show correct answers on result')),
                ('is_public', models.BooleanField(default=False, verbose_name='publicly visible')),
                ('is_organization_private', models.BooleanField(default=False, verbose_name='private to organizations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='authored_quizzes', to='judge.profile', verbose_name='creators')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'quiz category',
                'verbose_name_plural': 'quiz categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MC', 'Multiple Choice'), ('MA', 'Multiple Answer'), ('TF', 'True/False'), ('SA', 'Short Answer')], max_length=2, verbose_name='question type')),
                ('title', models.CharField(help_text='Short name to identify this question in the bank.', max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='question body')),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of choice texts (MC/MA only).', verbose_name='choices')),
                ('correct_answers', models.JSONField(blank=True, help_text='MC/TF: choice index. MA: list of indices. SA: list of {text, case_sensitive, is_regex}.', null=True, verbose_name='correct answers')),
                ('explanation', models.TextField(blank=True, help_text='Shown on the result page when the quiz allows it.', verbose_name='explanation')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=6, verbose_name='level')),
                ('shuffle_choices', models.BooleanField(default=False, verbose_name='shuffle choices')),
                ('ma_grading_strategy', models.CharField(choices=[('all_or_nothing', 'All or nothing'), ('partial_credit', 'Partial credit with penalty'), ('right_minus_wrong', 'Right minus wrong'), ('correct_only', 'Correct only, no penalty')], default='all_or_nothing', max_length=20, verbose_name='MA grading strategy')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to every quiz editor, not only authors.', verbose_name='publicly visible in bank')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='authored_quiz_questions', to='judge.profile', verbose_name='creators')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.quizcategory', verbose_name='category')),
                ('curators', models.ManyToManyField(blank=True, related_name='curated_quiz_questions', to='judge.profile', verbose_name='curators')),
            ],
            options={
                'verbose_name': 'quiz question',
                'verbose_name_plural': 'quiz questions',
                'ordering': ('-id',),
                'permissions': (('edit_all_quiz', 'Edit all quizzes and questions'), ('edit_own_quiz', 'Edit own quizzes and questions')),
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='points')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_links', to='quiz.quizquestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'quiz question link',
                'verbose_name_plural': 'quiz question links',
                'ordering': ('order', 'id'),
                'unique_together': {('quiz', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('is_submitted', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0, verbose_name='score')),
                ('question_order', models.JSONField(default=list)),
                ('choice_orders', models.JSONField(default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='judge.profile')),
            ],
            options={
                'verbose_name': 'quiz attempt',
                'verbose_name_plural': 'quiz attempts',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True)),
                ('points', models.FloatField(default=0.0)),
                ('is_correct', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.quizquestion')),
            ],
            options={
                'verbose_name': 'quiz answer',
                'verbose_name_plural': 'quiz answers',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quiz.quizcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='curators',
            field=models.ManyToManyField(blank=True, related_name='curated_quizzes', to='judge.profile', verbose_name='curators'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='judge.organization', verbose_name='organizations'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', through='quiz.QuizQuestionLink', to='quiz.quizquestion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='testers',
            field=models.ManyToManyField(blank=True, help_text='These users can take the quiz while it is private.', related_name='tested_quizzes', to='judge.profile', verbose_name='testers'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user', 'is_submitted'], name='quiz_quizat_quiz_id_3b72ed_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'is_submitted', 'score'], name='quiz_quizat_quiz_id_7b6ee4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
