# Generated by Django 4.2.30 on 2026-06-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_category_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('MA', 'Multiple Answer'), ('TF', 'True/False'), ('SA', 'Short Answer')], default='MC', max_length=2, verbose_name='question type'),
        ),
    ]
