# Generated by Django 4.2.30 on 2026-06-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizquestion_answer_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='integrity_monitoring',
            field=models.BooleanField(default=True, help_text='Track suspicious behavior during this quiz.', verbose_name='integrity monitoring'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='result_feedback',
            field=models.CharField(choices=[('score_only', 'Score only'), ('correctness', 'Show correctness (no answer key)'), ('full', 'Show correct answers and explanations')], default='full', help_text='Controls what students see on the result page after submitting. "Score only" — total score, no per-question detail. "Show correctness" — green/red per question, answer key hidden. "Show correct answers and explanations" — full feedback.', max_length=11, verbose_name='result feedback'),
        ),
        migrations.CreateModel(
            name='QuizViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tab_switch', 'Tab switch'), ('window_blur', 'Window blur'), ('devtools', 'DevTools opened'), ('print_screen', 'PrintScreen key'), ('copy_attempt', 'Copy attempt')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('extra_data', models.JSONField(default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='quiz.quizattempt')),
            ],
            options={
                'verbose_name': 'quiz violation',
                'verbose_name_plural': 'quiz violations',
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['attempt'], name='quiz_quizvi_attempt_b5cfc8_idx')],
            },
        ),
    ]
