# Generated by Django 4.2.30 on 2026-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_quiz_result_feedback_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Leave blank for no closing time.', null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Leave blank to make the quiz available immediately.', null=True, verbose_name='start time'),
        ),
    ]
