# Generated by Django 4.2.27 on 2026-04-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0215_populate_vote_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemEditorialReveal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='revealed at')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_reveals', to='judge.problem', verbose_name='problem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_reveals', to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'problem editorial reveal',
                'verbose_name_plural': 'problem editorial reveals',
                'unique_together': {('profile', 'problem')},
            },
        ),
    ]
