# Generated by Django 4.2.30 on 2026-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0216_problemeditorialreveal'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='block_copy',
            field=models.BooleanField(default=False, help_text='Block text selection and show a warning on the problem description page.', verbose_name='block copy'),
        ),
    ]
