# Generated by Django 4.2.30 on 2026-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0216_problemeditorialreveal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='testcase_visibility_mode',
            field=models.CharField(choices=[('O', 'Visible for authors'), ('C', 'Visible if user is not in a contest'), ('A', 'Always visible')], default='C', max_length=1, verbose_name='Testcase visibility'),
        ),
    ]
