# Generated by Django 4.2.30 on 2026-08-17 07:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import judge.models.library


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0216_problemeditorialreveal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'exam category',
                'verbose_name_plural': 'exam categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('province', models.CharField(blank=True, choices=[('ha_noi', 'Hà Nội'), ('tp_ho_chi_minh', 'TP. Hồ Chí Minh'), ('hai_phong', 'Hải Phòng'), ('da_nang', 'Đà Nẵng'), ('can_tho', 'Cần Thơ'), ('an_giang', 'An Giang'), ('ba_ria_vung_tau', 'Bà Rịa - Vũng Tàu'), ('bac_giang', 'Bắc Giang'), ('bac_kan', 'Bắc Kạn'), ('bac_lieu', 'Bạc Liêu'), ('bac_ninh', 'Bắc Ninh'), ('ben_tre', 'Bến Tre'), ('binh_dinh', 'Bình Định'), ('binh_duong', 'Bình Dương'), ('binh_phuoc', 'Bình Phước'), ('binh_thuan', 'Bình Thuận'), ('ca_mau', 'Cà Mau'), ('cao_bang', 'Cao Bằng'), ('dak_lak', 'Đắk Lắk'), ('dak_nong', 'Đắk Nông'), ('dien_bien', 'Điện Biên'), ('dong_nai', 'Đồng Nai'), ('dong_thap', 'Đồng Tháp'), ('gia_lai', 'Gia Lai'), ('ha_giang', 'Hà Giang'), ('ha_nam', 'Hà Nam'), ('ha_tinh', 'Hà Tĩnh'), ('hai_duong', 'Hải Dương'), ('hau_giang', 'Hậu Giang'), ('hoa_binh', 'Hòa Bình'), ('hung_yen', 'Hưng Yên'), ('khanh_hoa', 'Khánh Hòa'), ('kien_giang', 'Kiên Giang'), ('kon_tum', 'Kon Tum'), ('lai_chau', 'Lai Châu'), ('lam_dong', 'Lâm Đồng'), ('lang_son', 'Lạng Sơn'), ('lao_cai', 'Lào Cai'), ('long_an', 'Long An'), ('nam_dinh', 'Nam Định'), ('nghe_an', 'Nghệ An'), ('ninh_binh', 'Ninh Bình'), ('ninh_thuan', 'Ninh Thuận'), ('phu_tho', 'Phú Thọ'), ('phu_yen', 'Phú Yên'), ('quang_binh', 'Quảng Bình'), ('quang_nam', 'Quảng Nam'), ('quang_ngai', 'Quảng Ngãi'), ('quang_ninh', 'Quảng Ninh'), ('quang_tri', 'Quảng Trị'), ('soc_trang', 'Sóc Trăng'), ('son_la', 'Sơn La'), ('tay_ninh', 'Tây Ninh'), ('thai_binh', 'Thái Bình'), ('thai_nguyen', 'Thái Nguyên'), ('thanh_hoa', 'Thanh Hóa'), ('thua_thien_hue', 'Thừa Thiên Huế'), ('tien_giang', 'Tiền Giang'), ('tra_vinh', 'Trà Vinh'), ('tuyen_quang', 'Tuyên Quang'), ('vinh_long', 'Vĩnh Long'), ('vinh_phuc', 'Vĩnh Phúc'), ('yen_bai', 'Yên Bái')], default='', max_length=50, verbose_name='province')),
                ('year', models.IntegerField(blank=True, null=True, validators=[judge.models.library.validate_exam_year], verbose_name='year')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('pdf_url', models.CharField(blank=True, default='', max_length=200, verbose_name='PDF URL')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('publish_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish on')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='judge.examcategory', verbose_name='category')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_statements', to='judge.contest', verbose_name='contest')),
            ],
            options={
                'verbose_name': 'exam statement',
                'verbose_name_plural': 'exam statements',
                'ordering': ['-publish_on'],
            },
        ),
    ]
