# Generated by Django 4.2.30 on 2026-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0218_seed_exam_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstatement',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='publicly visible'),
        ),
    ]
