# Generated by Django 4.2.30 on 2026-08-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0219_library_public_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examstatement',
            options={'ordering': ['-publish_on'], 'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
    ]
