# Generated by Django 4.2.30 on 2026-08-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0220_alter_examstatement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstatement',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
