# Generated by Django 4.2.30 on 2026-08-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0218_set_testcase_visibility_always'),
        ('judge', '0221_alter_examstatement_slug'),
    ]

    operations = [
    ]
