# Generated by Django 4.2.30 on 2026-08-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0221_alter_examstatement_slug'),
        ('judge', '0232_organization_problem_tag'),
    ]

    operations = [
    ]
