# Generated by Django 4.2.30 on 2026-08-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0222_merge_20260818_0536'),
        ('judge', '0233_merge_20260818_0918'),
    ]

    operations = [
    ]
